DROP TABLE `collectionToEvents`;--> statement-breakpoint
DROP TABLE `collections`;--> statement-breakpoint
DROP TABLE `donations`;--> statement-breakpoint
DROP TABLE `event_claim_tokens`;--> statement-breakpoint
DROP TABLE `eventEditHistory`;--> statement-breakpoint
DROP TABLE `eventFeedback`;--> statement-breakpoint
DROP TABLE `eventTemplates`;--> statement-breakpoint
DROP TABLE `eventToEventTypes`;--> statement-breakpoint
DROP TABLE `eventTypeClicks`;--> statement-breakpoint
DROP TABLE `eventTypes`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `featureRequestUpvotes`;--> statement-breakpoint
DROP TABLE `featureRequests`;--> statement-breakpoint
DROP TABLE `featuredEvents`;--> statement-breakpoint
DROP TABLE `feedbackTemplates`;--> statement-breakpoint
DROP TABLE `magicLinkTokens`;--> statement-breakpoint
DROP TABLE `organizerImages`;--> statement-breakpoint
DROP TABLE `organizers`;--> statement-breakpoint
DROP TABLE `savedEvents`;--> statement-breakpoint
DROP TABLE `savedLocations`;--> statement-breakpoint
DROP TABLE `verificationRequests`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `pendingEmail`;