/**
 * Canadian provinces and territories with their major cities
 */

export const CANADIAN_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
] as const;

export const CANADIAN_CITIES: Record<string, string[]> = {
  AB: [
    "Calgary",
    "Edmonton",
    "Red Deer",
    "Lethbridge",
    "St. Albert",
    "Medicine Hat",
    "Grande Prairie",
    "Airdrie",
    "Spruce Grove",
    "Leduc",
    "Fort McMurray",
    "Camrose",
  ],
  BC: [
    "Vancouver",
    "Victoria",
    "Surrey",
    "Burnaby",
    "Richmond",
    "Abbotsford",
    "Coquitlam",
    "Kelowna",
    "Langley",
    "Saanich",
    "Delta",
    "Kamloops",
    "Nanaimo",
    "Prince George",
    "Chilliwack",
    "Vernon",
    "Penticton",
  ],
  MB: [
    "Winnipeg",
    "Brandon",
    "Steinbach",
    "Thompson",
    "Portage la Prairie",
    "Winkler",
    "Selkirk",
    "Morden",
    "Dauphin",
  ],
  NB: [
    "Moncton",
    "Saint John",
    "Fredericton",
    "Dieppe",
    "Miramichi",
    "Bathurst",
    "Edmundston",
    "Campbellton",
  ],
  NL: [
    "St. John's",
    "Mount Pearl",
    "Corner Brook",
    "Conception Bay South",
    "Paradise",
    "Grand Falls-Windsor",
    "Gander",
  ],
  NS: [
    // Regional Municipalities
    "Cape Breton Regional Municipality",
    "Halifax Regional Municipality",
    "Region of Queens Municipality",
    "West Hants Regional Municipality",
    // County Municipalities
    "Municipality of the County of Annapolis",
    "Municipality of the County of Antigonish",
    "Municipality of the County of Colchester",
    "Municipality of the County of Cumberland",
    "Municipality of the County of Inverness",
    "Municipality of the County of Kings",
    "Municipality of the County of Pictou",
    "Municipality of the County of Richmond",
    "Municipality of the County of Victoria",
    // District Municipalities
    "Municipality of the District of Argyle",
    "Municipality of the District of Barrington",
    "Municipality of the District of Chester",
    "Municipality of the District of Clare",
    "Municipality of the District of Digby",
    "Municipality of the District of East Hants",
    "Municipality of the District of Guysborough",
    "Municipality of the District of Lunenburg",
    "Municipality of the District of Shelburne",
    "Municipality of the District of St. Mary's",
    "Municipality of the District of Yarmouth",
    // Towns
    "Amherst",
    "Annapolis Royal",
    "Antigonish",
    "Berwick",
    "Bridgewater",
    "Clark's Harbour",
    "Digby",
    "Kentville",
    "Lockeport",
    "Lunenburg",
    "Mahone Bay",
    "Middleton",
    "Mulgrave",
    "New Glasgow",
    "Oxford",
    "Pictou",
    "Port Hawkesbury",
    "Shelburne",
    "Stellarton",
    "Stewiacke",
    "Trenton",
    "Truro",
    "Westville",
    "Wolfville",
  ],
  NT: [
    "Yellowknife",
    "Hay River",
    "Inuvik",
    "Fort Smith",
    "Behchokǫ̀",
  ],
  NU: [
    "Iqaluit",
    "Rankin Inlet",
    "Arviat",
    "Baker Lake",
    "Cambridge Bay",
  ],
  ON: [
    "Toronto",
    "Ottawa",
    "Mississauga",
    "Brampton",
    "Hamilton",
    "London",
    "Markham",
    "Vaughan",
    "Kitchener",
    "Windsor",
    "Richmond Hill",
    "Oakville",
    "Burlington",
    "Sudbury",
    "Oshawa",
    "Barrie",
    "St. Catharines",
    "Cambridge",
    "Kingston",
    "Guelph",
    "Waterloo",
    "Thunder Bay",
    "Peterborough",
    "Niagara Falls",
    "Brantford",
  ],
  PE: [
    "Charlottetown",
    "Summerside",
    "Stratford",
    "Cornwall",
  ],
  QC: [
    "Montreal",
    "Quebec City",
    "Laval",
    "Gatineau",
    "Longueuil",
    "Sherbrooke",
    "Saguenay",
    "Trois-Rivières",
    "Terrebonne",
    "Saint-Jean-sur-Richelieu",
    "Repentigny",
    "Brossard",
    "Drummondville",
    "Saint-Jérôme",
    "Granby",
  ],
  SK: [
    "Saskatoon",
    "Regina",
    "Prince Albert",
    "Moose Jaw",
    "Swift Current",
    "Yorkton",
    "North Battleford",
    "Estevan",
  ],
  YT: [
    "Whitehorse",
    "Dawson City",
    "Watson Lake",
  ],
};
