/**
 * Canadian provinces and territories with their cities, towns, and municipalities
 * Includes all cities, larger towns (5,000+ population), regional municipalities, and popular destinations
 */

export const CANADIAN_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
] as const;

export const CANADIAN_CITIES: Record<string, string[]> = {
  AB: [
    "Airdrie",
    "Banff",
    "Beaumont",
    "Bon Accord",
    "Brooks",
    "Calgary",
    "Camrose",
    "Canmore",
    "Chestermere",
    "Cochrane",
    "Cold Lake",
    "Devon",
    "Drayton Valley",
    "Edmonton",
    "Fort McMurray",
    "Fort Saskatchewan",
    "Grande Prairie",
    "High River",
    "Hinton",
    "Jasper",
    "Lacombe",
    "Leduc",
    "Lethbridge",
    "Lloydminster",
    "Medicine Hat",
    "Okotoks",
    "Olds",
    "Ponoka",
    "Red Deer",
    "Rocky Mountain House",
    "Sherwood Park",
    "Spruce Grove",
    "St. Albert",
    "Stony Plain",
    "Strathmore",
    "Sylvan Lake",
    "Taber",
    "Vegreville",
    "Vermilion",
    "Wainwright",
    "Wetaskiwin",
    "Whitecourt",
    "Wood Buffalo",
  ],
  BC: [
    "Abbotsford",
    "Armstrong",
    "Burnaby",
    "Campbell River",
    "Castlegar",
    "Chilliwack",
    "Colwood",
    "Comox",
    "Coquitlam",
    "Courtenay",
    "Cranbrook",
    "Dawson Creek",
    "Delta",
    "Duncan",
    "Fernie",
    "Fort St. John",
    "Grand Forks",
    "Invermere",
    "Kamloops",
    "Kelowna",
    "Kimberley",
    "Langford",
    "Langley",
    "Maple Ridge",
    "Merritt",
    "Mission",
    "Nanaimo",
    "Nelson",
    "New Westminster",
    "North Vancouver",
    "Parksville",
    "Penticton",
    "Pitt Meadows",
    "Port Alberni",
    "Port Coquitlam",
    "Port Moody",
    "Powell River",
    "Prince George",
    "Prince Rupert",
    "Qualicum Beach",
    "Quesnel",
    "Revelstoke",
    "Richmond",
    "Rossland",
    "Saanich",
    "Salmon Arm",
    "Sidney",
    "Smithers",
    "Squamish",
    "Surrey",
    "Terrace",
    "Trail",
    "Vancouver",
    "Vernon",
    "Victoria",
    "West Kelowna",
    "West Vancouver",
    "Whistler",
    "White Rock",
    "Williams Lake",
  ],
  MB: [
    "Brandon",
    "Dauphin",
    "Flin Flon",
    "Morden",
    "Portage la Prairie",
    "Selkirk",
    "Steinbach",
    "Thompson",
    "Winkler",
    "Winnipeg",
  ],
  NB: [
    "Bathurst",
    "Campbellton",
    "Dieppe",
    "Edmundston",
    "Fredericton",
    "Grand Falls",
    "Miramichi",
    "Moncton",
    "Oromocto",
    "Quispamsis",
    "Riverview",
    "Rothesay",
    "Saint John",
    "Sackville",
    "Shediac",
    "Sussex",
    "Woodstock",
  ],
  NL: [
    "Bay Roberts",
    "Carbonear",
    "Channel-Port aux Basques",
    "Conception Bay South",
    "Corner Brook",
    "Gander",
    "Grand Falls-Windsor",
    "Happy Valley-Goose Bay",
    "Labrador City",
    "Marystown",
    "Mount Pearl",
    "Paradise",
    "Placentia",
    "Portugal Cove-St. Philip's",
    "St. John's",
    "Stephenville",
    "Torbay",
  ],
  NS: [
    // Regional Municipalities
    "Cape Breton Regional Municipality",
    "Halifax Regional Municipality",
    "Region of Queens Municipality",
    "West Hants Regional Municipality",
    // County Municipalities
    "Municipality of the County of Annapolis",
    "Municipality of the County of Antigonish",
    "Municipality of the County of Colchester",
    "Municipality of the County of Cumberland",
    "Municipality of the County of Inverness",
    "Municipality of the County of Kings",
    "Municipality of the County of Pictou",
    "Municipality of the County of Richmond",
    "Municipality of the County of Victoria",
    // District Municipalities
    "Municipality of the District of Argyle",
    "Municipality of the District of Barrington",
    "Municipality of the District of Chester",
    "Municipality of the District of Clare",
    "Municipality of the District of Digby",
    "Municipality of the District of East Hants",
    "Municipality of the District of Guysborough",
    "Municipality of the District of Lunenburg",
    "Municipality of the District of Shelburne",
    "Municipality of the District of St. Mary's",
    "Municipality of the District of Yarmouth",
    // Towns
    "Amherst",
    "Annapolis Royal",
    "Antigonish",
    "Berwick",
    "Bridgewater",
    "Clark's Harbour",
    "Digby",
    "Kentville",
    "Lockeport",
    "Lunenburg",
    "Mahone Bay",
    "Middleton",
    "Mulgrave",
    "New Glasgow",
    "Oxford",
    "Pictou",
    "Port Hawkesbury",
    "Shelburne",
    "Stellarton",
    "Stewiacke",
    "Trenton",
    "Truro",
    "Westville",
    "Wolfville",
  ],
  NT: [
    "Behchokǫ̀",
    "Fort Simpson",
    "Fort Smith",
    "Hay River",
    "Inuvik",
    "Norman Wells",
    "Yellowknife",
  ],
  NU: [
    "Arviat",
    "Baker Lake",
    "Cambridge Bay",
    "Gjoa Haven",
    "Iqaluit",
    "Kugluktuk",
    "Pond Inlet",
    "Rankin Inlet",
  ],
  ON: [
    "Ajax",
    "Amherstburg",
    "Aurora",
    "Barrie",
    "Belleville",
    "Bracebridge",
    "Brampton",
    "Brant",
    "Brantford",
    "Brockville",
    "Burlington",
    "Cambridge",
    "Clarence-Rockland",
    "Cobourg",
    "Collingwood",
    "Cornwall",
    "Dryden",
    "Essex",
    "Gananoque",
    "Georgina",
    "Guelph",
    "Haldimand County",
    "Halton Hills",
    "Hamilton",
    "Huntsville",
    "Ingersoll",
    "Kawartha Lakes",
    "Kenora",
    "Kingston",
    "Kingsville",
    "Kitchener",
    "LaSalle",
    "Leamington",
    "Lincoln",
    "London",
    "Markham",
    "Milton",
    "Mississauga",
    "Muskoka",
    "Newmarket",
    "Niagara Falls",
    "Niagara-on-the-Lake",
    "Norfolk County",
    "North Bay",
    "Oakville",
    "Orangeville",
    "Orillia",
    "Oshawa",
    "Ottawa",
    "Owen Sound",
    "Parry Sound",
    "Pembroke",
    "Peterborough",
    "Pickering",
    "Port Colborne",
    "Port Hope",
    "Prince Edward County",
    "Quinte West",
    "Richmond Hill",
    "Sarnia",
    "Sault Ste. Marie",
    "Smiths Falls",
    "St. Catharines",
    "St. Thomas",
    "Stratford",
    "Sudbury",
    "Tecumseh",
    "Thorold",
    "Thunder Bay",
    "Timmins",
    "Toronto",
    "Vaughan",
    "Wasaga Beach",
    "Waterloo",
    "Welland",
    "Whitby",
    "Windsor",
    "Woodstock",
  ],
  PE: [
    "Alberton",
    "Charlottetown",
    "Cornwall",
    "Kensington",
    "Montague",
    "Souris",
    "Stratford",
    "Summerside",
  ],
  QC: [
    "Alma",
    "Amos",
    "Baie-Comeau",
    "Beaconsfield",
    "Beauharnois",
    "Blainville",
    "Boisbriand",
    "Boucherville",
    "Brossard",
    "Candiac",
    "Chambly",
    "Châteauguay",
    "Côte-Saint-Luc",
    "Dollard-des-Ormeaux",
    "Dorval",
    "Drummondville",
    "Gatineau",
    "Granby",
    "Joliette",
    "La Prairie",
    "Lachute",
    "Laval",
    "Lévis",
    "Longueuil",
    "Magog",
    "Mascouche",
    "Matane",
    "Mirabel",
    "Mont-Laurier",
    "Mont-Royal",
    "Mont-Tremblant",
    "Montreal",
    "Pointe-Claire",
    "Quebec City",
    "Repentigny",
    "Rimouski",
    "Rouyn-Noranda",
    "Saguenay",
    "Saint-Bruno-de-Montarville",
    "Saint-Constant",
    "Saint-Eustache",
    "Saint-Georges",
    "Saint-Hyacinthe",
    "Saint-Jean-sur-Richelieu",
    "Saint-Jérôme",
    "Saint-Lambert",
    "Saint-Lazare",
    "Sainte-Julie",
    "Sainte-Thérèse",
    "Salaberry-de-Valleyfield",
    "Sept-Îles",
    "Shawinigan",
    "Sherbrooke",
    "Sorel-Tracy",
    "Terrebonne",
    "Thetford Mines",
    "Trois-Rivières",
    "Val-d'Or",
    "Varennes",
    "Vaudreuil-Dorion",
    "Victoriaville",
    "Westmount",
  ],
  SK: [
    "Estevan",
    "Humboldt",
    "Lloydminster",
    "Martensville",
    "Meadow Lake",
    "Melfort",
    "Melville",
    "Moose Jaw",
    "North Battleford",
    "Prince Albert",
    "Regina",
    "Saskatoon",
    "Swift Current",
    "Warman",
    "Weyburn",
    "Yorkton",
  ],
  YT: [
    "Carcross",
    "Carmacks",
    "Dawson City",
    "Faro",
    "Haines Junction",
    "Mayo",
    "Teslin",
    "Watson Lake",
    "Whitehorse",
  ],
};
